-- ============================================================
-- MusicTutor Database Schema
-- ============================================================

-- 0. Helper function for updated_at triggers
create or replace function handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- 1. profiles
-- ============================================================
create table profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  name        text,
  avatar_url  text,
  role        text not null check (role in ('student', 'tutor')) default 'student',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index idx_profiles_role on profiles(role);

create trigger trg_profiles_updated_at
  before update on profiles
  for each row execute function handle_updated_at();

alter table profiles enable row level security;

create policy "authenticated users can read profiles"
  on profiles for select
  to authenticated
  using (true);

create policy "users can insert their own profile"
  on profiles for insert
  to authenticated
  with check (id = auth.uid());

create policy "users can update their own profile"
  on profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ============================================================
-- 2. student_profiles
-- ============================================================
create table student_profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  instruments   text[] not null default '{}',
  experience    text not null default 'beginner' check (experience in ('beginner', 'some', 'intermediate', 'advanced')),
  goal          text not null default 'fun' check (goal in ('fun', 'basics', 'perform', 'competitive')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index idx_student_profiles_experience on student_profiles(experience);
create index idx_student_profiles_goal on student_profiles(goal);

create trigger trg_student_profiles_updated_at
  before update on student_profiles
  for each row execute function handle_updated_at();

alter table student_profiles enable row level security;

create policy "authenticated users can read student_profiles"
  on student_profiles for select
  to authenticated
  using (true);

create policy "students can insert their own student_profile"
  on student_profiles for insert
  to authenticated
  with check (id = auth.uid());

create policy "students can update their own student_profile"
  on student_profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ============================================================
-- 3. tutor_profiles
-- ============================================================
create table tutor_profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  instruments       text[] not null default '{}',
  teaching_style    text not null default 'balanced' check (teaching_style in ('casual', 'balanced', 'focused', 'rigorous')),
  student_preference text not null default 'all' check (student_preference in ('beginners', 'all', 'intermediate', 'advanced')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index idx_tutor_profiles_teaching_style on tutor_profiles(teaching_style);
create index idx_tutor_profiles_student_preference on tutor_profiles(student_preference);

create trigger trg_tutor_profiles_updated_at
  before update on tutor_profiles
  for each row execute function handle_updated_at();

alter table tutor_profiles enable row level security;

create policy "authenticated users can read tutor_profiles"
  on tutor_profiles for select
  to authenticated
  using (true);

create policy "tutors can insert their own tutor_profile"
  on tutor_profiles for insert
  to authenticated
  with check (id = auth.uid());

create policy "tutors can update their own tutor_profile"
  on tutor_profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ============================================================
-- 4. lesson_requests
-- ============================================================
create table lesson_requests (
  id                  bigint generated by default as identity primary key,
  student_id          uuid not null references auth.users(id) on delete cascade,
  tutor_id            uuid not null references auth.users(id) on delete cascade,
  student_instruments text[] not null default '{}',
  student_experience  text not null,
  student_goal        text not null,
  status              text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index idx_lesson_requests_student_id on lesson_requests(student_id);
create index idx_lesson_requests_tutor_id on lesson_requests(tutor_id);
create index idx_lesson_requests_status on lesson_requests(status);

create trigger trg_lesson_requests_updated_at
  before update on lesson_requests
  for each row execute function handle_updated_at();

alter table lesson_requests enable row level security;

create policy "authenticated users can read lesson_requests"
  on lesson_requests for select
  to authenticated
  using (true);

create policy "students can create lesson_requests"
  on lesson_requests for insert
  to authenticated
  with check (student_id = auth.uid());

create policy "tutors can update lesson_request status"
  on lesson_requests for update
  to authenticated
  using (tutor_id = auth.uid())
  with check (tutor_id = auth.uid() and status in ('accepted', 'declined'));